# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "ruby-debug-ide", "~> 0.7.2"

gem "debase", "~> 0.2.4"
