# https://blog.mergify.com/strict-mode-deprecation/
queue_rules:
  - name: default
    # These define the conditions to get out of the merge queue
    conditions:
      # CI https://doc.mergify.io/conditions.html#github-actions
      - status-success=PythonLint
      - status-success=VimscriptLint
      - status-success=Linux
      - status-success=MacOS

pull_request_rules:
  - name: Merge owner PR when all checks passed
    # These define the conditions to get into the merge queue
    conditions:
      - author=puremourning
      - base=master
      # Review
      - status-success=code-review/reviewable
      - "#changes-requested-reviews-by=0"
      # CI https://doc.mergify.io/conditions.html#github-actions
      - status-success=PythonLint
      - status-success=VimscriptLint
      - status-success=Linux
      - status-success=MacOS
    actions: &merge-actions
      queue:
        method: merge
        name: default
      delete_head_branch: {}

  - name: Merge auto pr when approved
    conditions:
      - author=github-actions
      - label=auto
      - base=master
      # Review
      - status-success=code-review/reviewable
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
    actions: &merge-actions
      queue:
        method: merge
        name: default
      delete_head_branch: {}

  - name: Merge PR when all checks passed
    # These define the conditions to get into the merge queue
    conditions:
      - author!=puremourning
      - base=master
      # Review
      - status-success=code-review/reviewable
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - approved-reviews-by=puremourning
      # CI https://doc.mergify.io/conditions.html#github-actions
      - status-success=PythonLint
      - status-success=VimscriptLint
      - status-success=Linux
      - status-success=MacOS
    actions:
      <<: *merge-actions
      comment:
        message: Thanks for sending a PR!
