# https://blog.mergify.com/strict-mode-deprecation/
queue_rules:
  - name: duplicated default from Merge owner PR when all checks passed
    queue_conditions:
      - author=puremourning
      - base=master
      - status-success=code-review/reviewable
      - "#changes-requested-reviews-by=0"
      - status-success=PythonLint
      - status-success=VimscriptLint
      - status-success=Linux (vim)
      - status-success=Linux (nvim)
      - status-success=MacOS (vim)
    merge_conditions:
      # CI https://doc.mergify.io/conditions.html#github-actions
      - status-success=PythonLint
      - status-success=VimscriptLint
      - status-success=Linux (vim)
      - status-success=Linux (nvim)
      - status-success=MacOS (vim)
      #- status-success=MacOS (nvim)

    merge_method: merge
  - name: duplicated default from Merge auto pr when approved
    queue_conditions:
      - author=VimspectorUpdateBot
      - label=auto
      - base=master
      - status-success=code-review/reviewable
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
    merge_conditions:
      # CI https://doc.mergify.io/conditions.html#github-actions
      - status-success=PythonLint
      - status-success=VimscriptLint
      - status-success=Linux (vim)
      - status-success=Linux (nvim)
      - status-success=MacOS (vim)
      #- status-success=MacOS (nvim)

    merge_method: merge
  - name: duplicated default from Merge PR when all checks passed
    queue_conditions:
      - author!=puremourning
      - base=master
      - status-success=code-review/reviewable
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - approved-reviews-by=puremourning
      - status-success=PythonLint
      - status-success=VimscriptLint
      - status-success=Linux (vim)
      - status-success=Linux (nvim)
      - status-success=MacOS (vim)
    merge_conditions:
      # CI https://doc.mergify.io/conditions.html#github-actions
      - status-success=PythonLint
      - status-success=VimscriptLint
      - status-success=Linux (vim)
      - status-success=Linux (nvim)
      - status-success=MacOS (vim)
      #- status-success=MacOS (nvim)

    merge_method: merge
  - name: default
    # These define the conditions to get out of the merge queue
    conditions:
      # CI https://doc.mergify.io/conditions.html#github-actions
      - status-success=PythonLint
      - status-success=VimscriptLint
      - status-success=Linux (vim)
      - status-success=Linux (nvim)
      - status-success=MacOS (vim)
      #- status-success=MacOS (nvim)


pull_request_rules:
  - name: Merge owner PR when all checks passed
    # These define the conditions to get into the merge queue
    conditions:
      - author=puremourning
      - base=master
      # Review
      - status-success=code-review/reviewable
      - "#changes-requested-reviews-by=0"
      # CI https://doc.mergify.io/conditions.html#github-actions
      - status-success=PythonLint
      - status-success=VimscriptLint
      - status-success=Linux (vim)
      - status-success=Linux (nvim)
      - status-success=MacOS (vim)
      #- status-success=MacOS (nvim)
    actions: &merge-actions
      delete_head_branch: {}
  - name: Merge auto pr when approved
    conditions:
      - author=VimspectorUpdateBot
      - label=auto
      - base=master
      # Review
      - status-success=code-review/reviewable
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
    actions:
      <<: *merge-actions
  - name: Merge PR when all checks passed
    # These define the conditions to get into the merge queue
    conditions:
      - author!=puremourning
      - base=master
      # Review
      - status-success=code-review/reviewable
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - approved-reviews-by=puremourning
      # CI https://doc.mergify.io/conditions.html#github-actions
      - status-success=PythonLint
      - status-success=VimscriptLint
      - status-success=Linux (vim)
      - status-success=Linux (nvim)
      - status-success=MacOS (vim)
      #- status-success=MacOS (nvim)
    actions:
      <<: *merge-actions
      comment:
        message: Thanks for sending a PR!
  - name: Merge PR when all checks passed + Merge auto pr when approved + Merge owner
      PR when all checks passed
    conditions: []
    actions:
      queue:
