#!/usr/bin/env bash

OS=$1
shift

VERSION=$1
shift

ROOT=$(pwd)
PACK=${ROOT}/package/${OS}

pushd ${PACK}
  mkdir -p vimspector/opt
  mkdir -p vimspector/start
  pushd vimspector/start
    for d in autoload plugin python3 vendor doc; do
      if [[ -d ${ROOT}/$d ]]; then
        cp -r ${ROOT}/$d .
      fi
    done
    mkdir -p gadgets
    pushd gadgets
      cp ${ROOT}/gadgets/.gadgets.json .
      cp -r ${ROOT}/gadgets/${OS} .
    popd
  popd
popd

cd ${ROOT}/package
tar zcvf ${OS}-${VERSION}.tar.gz ${OS}/
