#!/usr/bin/env bash

set -e
set -x

tmpdir=$(mktemp -d)
python3 -m venv ${tmpdir}/env
source ${tmpdir}/env/bin/activate

git clone https://github.com/ycm-core/vim-tools ${tmpdir}/vim-tools

pip install -r ${tmpdir}/vim-tools/requirements.txt

pushd $(dirname $0)
  python3 ${tmpdir}/vim-tools/html2vimdoc.py -f vimspector \
                                             README.md \
                                             > doc/vimspector.txt
  python3 ${tmpdir}/vim-tools/html2vimdoc.py -f vimspector-ref \
                                             docs/configuration.md \
                                             > doc/vimspector-ref.txt
popd

deactivate

rm -rf ${tmpdir}
