#!/usr/bin/env bash

CONTAINER=puremourning/vimspector:manual-$(uname -m )

docker run --cap-add=SYS_PTRACE \
           --security-opt seccomp=unconfined \
           --mount src="$(pwd)/../..",target=/home/dev/vimspector,type=bind \
           -it ${CONTAINER} \
           "$@"
