let g:vimspector_test_plugin_path = expand( '<sfile>:p:h:h' )
set mouse=a
set noequalalways
let mapleader = ','
let maplocalleader = "\<Space>"

let &runtimepath = &runtimepath . ',' . g:vimspector_test_plugin_path

filetype plugin indent on
syntax enable
