let g:vimspector_test_plugin_path = expand( '<sfile>:p:h:h' )
set mouse=a
set noequalalways
let mapleader = ','
let maplocalleader = "\<Space>"
let g:vimspector_install_gadgets=[ '--all', 'netcoredbg', 'vscode-js-debug' ]

if exists( '$VIMSPECTOR_TEST_BASE' )
  let g:vimspector_base_dir = g:vimspector_test_plugin_path .. '/' .. $VIMSPECTOR_TEST_BASE
endif

if has('nvim' ) && exists( 'g:vimspector_base_dir' )
  \ && isdirectory( g:vimspector_base_dir . '/nvim_env' )
  let g:python3_host_prog = g:vimspector_base_dir . '/nvim_env/bin/python'
endif

let &runtimepath = &runtimepath . ',' . g:vimspector_test_plugin_path

filetype plugin indent on
syntax enable
