#!/usr/bin/env bash

set -e

if [ "$1" = "--clean" ]; then
  OPTS="--no-cache"
else
  OPTS=""
fi

ARCH=$(uname -m)

GOARCH=${ARCH}
if [ "${ARCH}" = "x86_64" ]; then
  GOARCH=amd64
fi

docker build ${OPTS} --build-arg GOARCH=${GOARCH} \
                     -t puremourning/vimspector:test-${ARCH} image/
